### ISSUE TITLE
gnome-shell fails to start after 2.0.0

### ISSUE THREAD

**Issue by MKuranowski** [linux-surface/libwacom#4]
Arch Linux, Surface Go 1. After upgrading `libwacom-surface` to 2.0.0 `gnome-shell` fails to start (both on Wayland an Xorg) with a missing `libwacom.so.2` library.

The full log message is:
```
gnome-shell: error while loading shared libraries: libwacom.so.2: cannot open shared object file: No such file or directory
```

Don't know the details, but it might be worthwhile to wait until the non-patched `libwacom` package in mainstream gets updated to 2.0.0.

**Comment by qzed** [comment]
Sorry for the inconvenience. I've reverted back to libwacom-1.12.1.

Depending on the package manager, you may have to explicitly downgrade. You may need to go into a tty for that (e.g. via Ctrl+Alt+F3) if the desktop is broken.

Related to https://github.com/linux-surface/linux-surface/issues/709.

**Comment by MKuranowski** [comment]
Actually, I think that breaks input completely, and Ctrl+Alt+F.. didn't really work for me. I had to chroot from the installation USB to downgrade the package.

**Comment by qzed** [comment]
Booting to the recovery mode/terminal would be another possibility. That should be an option in your bootloader.

**Comment by SimonSchwendele** [comment]
No recovery mode disables terminal as well 😆

**Comment by qzed** [comment]
IIRC you should be able to boot into recovery mode and go on from there. If you can't directly do that there (e.g. this might drop you into the initrd or something), `systemctl isolate multi-user.target` should be able to get you to a "normal" terminal without trying to start any desktop stuff. Been a while since I had to hack around with that though, so I might be wrong.

**Comment by qzed** [comment]
And as a last option, you can also temporarily add `systemd.unit=multi-user.target` to the kernel commandline. All of that assumes you're using systemd of course.

**Comment by SimonSchwendele** [comment]
Pop uses systemd boot.
Worth a shot

**Comment by SimonSchwendele** [comment]
Working again thanks for the update.
I had to set my default.target to runlevel1 to make it start but then i could isolate and perform the upgrade

**Comment by qzed** [comment]
Closing as this should be fixed.
