### ISSUE TITLE
Libwacom surface package breaks Manjaro

### ISSUE THREAD

**Issue by ianoxian** [linux-surface/libwacom#5]
Installing libwacom-surface via AUR breaks my current installation of Manjaro (Qonos)  Gnome.

As soon as the display-manager is supposed to start, I get an error message saying "something happened that the system cannot handle. please contact your sys-admin".  I can only hard-reset my machine: no switching to other TTY's, no ctrl-alt-delete or else is working. I suspect it has something to do with IPMI_si, saying it is unable to find any system interfaces.

Attached is a complete "journalctl -b -1" log 
[lastboot.log](https://github.com/linux-surface/libwacom/files/7917596/lastboot.log)

Replacing libwacom-surface with the normal libwacom fixes the problem, re-installing libwacom-surface introduces the bug again.
Using a Microsoft Surface 6 Pro here.

Let me know if I can do anything to assist to debug this.

**Comment by qzed** [comment]
There's nothing I can do about this, sorry. The only thing you can do is downgrade libwacom-surface for the time being.

This is happening because Gnome has to be compiled for the respective libwacom version. On Arch, Gnome has been compiled for libwacom-2.x. Hence the AUR version is libwacom-2.0.0 (as libwacom-1.x would break the system in the same way you describe). On Manjaro, it seems, Gnome has been compiled for libwacom-1.x, so it breaks if you install libwacom-2.x.

**Comment by ianoxian** [comment]
Couldn't the installation of libwacom-2.0.0 be prevented with checks for Gnome actually being compiled for this version? I don't know, dependecy checks or something similar?
Still, thank you for clarifying this issue and letting me know the cause of this unexpected loss of my operating system.

**Comment by qzed** [comment]
> Couldn't the installation of libwacom-2.0.0 be prevented with checks for Gnome actually being compiled for this version? I don't know, dependecy checks or something similar?

I don't think so. I'm pretty sure you can compile any version of Gnome against any version of libwacom, and there's no telling from the package which one it's been compiled against. If you or anyone knows any mechanism to check that at install time or something, please let me know.

**Comment by StollD** [comment]
Since the Manjaro packages are just the Arch packages delayed by two weeks, you should get the libwacom update within the next week.
